// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZX5_s2yWbYuByDo1eXoti9pji8RXzqJA',
    appId: '1:14723248471:web:a2265b5f1988cd7b568e12',
    messagingSenderId: '14723248471',
    projectId: 'e-commerce-app-30a02',
    authDomain: 'e-commerce-app-30a02.firebaseapp.com',
    storageBucket: 'e-commerce-app-30a02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6r5ttPyHn0RtZhmdN5t-lespPkKgyC1Y',
    appId: '1:14723248471:android:9412447beefe327f568e12',
    messagingSenderId: '14723248471',
    projectId: 'e-commerce-app-30a02',
    storageBucket: 'e-commerce-app-30a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdfDZXVvqt7YqriDpZRxe0D75HHGjBVzU',
    appId: '1:14723248471:ios:5aeaf1b35e42ba79568e12',
    messagingSenderId: '14723248471',
    projectId: 'e-commerce-app-30a02',
    storageBucket: 'e-commerce-app-30a02.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdfDZXVvqt7YqriDpZRxe0D75HHGjBVzU',
    appId: '1:14723248471:ios:5aeaf1b35e42ba79568e12',
    messagingSenderId: '14723248471',
    projectId: 'e-commerce-app-30a02',
    storageBucket: 'e-commerce-app-30a02.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZX5_s2yWbYuByDo1eXoti9pji8RXzqJA',
    appId: '1:14723248471:web:2389c6cb0f4ad4c2568e12',
    messagingSenderId: '14723248471',
    projectId: 'e-commerce-app-30a02',
    authDomain: 'e-commerce-app-30a02.firebaseapp.com',
    storageBucket: 'e-commerce-app-30a02.firebasestorage.app',
  );
}
